name: next-version

on: 
 push:
    
    
    tags:        
      - v1.*            
    
  

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Application Version
      id: v
      uses: anothrNick/github-tag-action@1.36.0
      with:
       WITH_V: true
     
          
         

          
