name: next-version

on: push
  

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Application Version
      id: version
      uses: paulhatch/semantic-version@v4.0.2
      with:
        change_path: "src/service"
          
         

          
