name: next-version

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      # Push events on main branch
      - master
      # Push events to branches matching refs/heads/mona/octocat
     #'mona/octocat'
      # Push events to branches matching refs/heads/releases/10
      #- 'releases/**'
    # Sequence of patterns matched against refs/tags
    tags:        
      - v1             # Push events to v1 tag
      - v1.* 
    

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Application Version
      id: version
      uses: anothrNick/github-tag-action@1.36.0
      with:
       WITH_V: true
     
          
         

          
