name: next-version

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      # Push events on main branch
      - master
      # Push events to branches matching refs/heads/mona/octocat
     #'mona/octocat'
      # Push events to branches matching refs/heads/releases/10
      #- 'releases/**'
    # Sequence of patterns matched against refs/tags
    tags:        
      - versionzz 
    

jobs:
   my_first_job:
    
  
     runs-on: ubuntu-latest
    
     steps:
      - name: Application Version
        id: version
        uses: anothrNick/github-tag-action@1.36.0
        with:
         WITH_V: true

   my_second_job:
    
  
       runs-on: ubuntu-latest   
       steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 11
          uses: actions/setup-java@v2
          with:
            java-version: '11'
            distribution: 'adopt'
            server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
            settings-path: ${{ github.workspace }} # location for the settings.xml file

        - name: Build with Maven
          run: mvn -B package --file pom.xml

        - name: Publish to GitHub Packages Apache Maven
          run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
          env:
            GITHUB_TOKEN: ${{ github.token }}




          
