name: next-version

on: push

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Application Version
      id: version
      uses: anothrNick/github-tag-action@1.36.0
      with:
       WITH_V: true
     
          
         

          
